import { Property, KPI, ChartData, Alert, Lease, WorkOrder, Activity, Task, Workflow, MaintenanceRequest } from '../types';

export const PROPERTIES: Property[] = [
  {
    id: 'P001',
    name: 'Suvarnabhumi Residence',
    address: '612/21 King Kaew Rd',
    city: 'Bangkok',
    type: 'Residential',
    status: 'Active',
    value: 15200000,
    occupancyRate: 92,
    monthlyRent: 12000,
    image: 'https://picsum.photos/400/300?random=1',
    tenantCount: 45,
    lastRenovated: '2022',
  },
  {
    id: 'P002',
    name: 'Airport Side Apartment',
    address: '613/21 Lat Krabang',
    city: 'Bangkok',
    type: 'Residential',
    status: 'Pending',
    value: 8400000,
    occupancyRate: 88,
    monthlyRent: 15000,
    image: 'https://picsum.photos/400/300?random=2',
    tenantCount: 22,
    lastRenovated: '2020',
  },
  {
    id: 'P003',
    name: 'Park Villa',
    address: '614/21 Phuket Town',
    city: 'Phuket',
    type: 'Commercial',
    status: 'Active',
    value: 22100000,
    occupancyRate: 95,
    monthlyRent: 18500,
    image: 'https://picsum.photos/400/300?random=3',
    tenantCount: 12,
    lastRenovated: '2023',
  },
  {
    id: 'P004',
    name: 'Sriracha View',
    address: '615/21 Sriracha',
    city: 'Chonburi',
    type: 'Office',
    status: 'Maintenance',
    value: 35000000,
    occupancyRate: 72,
    monthlyRent: 20000,
    image: 'https://picsum.photos/400/300?random=4',
    tenantCount: 8,
    lastRenovated: '2019',
  },
  {
    id: 'P005',
    name: 'Urban Chiang Mai',
    address: '621/21 Nimman',
    city: 'Chiang Mai',
    type: 'Commercial',
    status: 'Active',
    value: 18500000,
    occupancyRate: 98,
    monthlyRent: 22500,
    image: 'https://picsum.photos/400/300?random=5',
    tenantCount: 15,
    lastRenovated: '2024',
  },
  {
    id: 'P006',
    name: 'Urban Bang Phli',
    address: '623/21 Bang Phli',
    city: 'Samut Prakan',
    type: 'Residential',
    status: 'Active',
    value: 12000000,
    occupancyRate: 85,
    monthlyRent: 8500,
    image: 'https://picsum.photos/400/300?random=6',
    tenantCount: 30,
    lastRenovated: '2021',
  },
];

export const KPIS: KPI[] = [
  {
    label: 'Total Asset Portfolio',
    value: '102,000,000',
    trend: 6,
    trendLabel: 'since last month',
    isPositive: true,
  },
  {
    label: 'Total Occupancy Rate',
    value: '76%',
    trend: 2,
    trendLabel: 'last month',
    isPositive: true,
  },
  {
    label: 'Average Rent Yield',
    value: '5.2%',
    trend: 0.1,
    trendLabel: 'last month',
    isPositive: true,
  },
  {
    label: 'Vacant Properties',
    value: '12',
    trend: -2,
    trendLabel: 'rented out last month',
    isPositive: true, // In this context, decrease in vacancy is good
  },
];

export const REVENUE_DATA: ChartData[] = [
  { name: 'Jan', value: 1.2, value2: 1.0 },
  { name: 'Feb', value: 1.3, value2: 1.1 },
  { name: 'Mar', value: 1.4, value2: 1.2 },
  { name: 'Apr', value: 1.8, value2: 1.4 },
  { name: 'May', value: 2.0, value2: 1.5 },
  { name: 'Jun', value: 2.4, value2: 1.8 },
  { name: 'Jul', value: 2.2, value2: 1.9 },
  { name: 'Aug', value: 2.6, value2: 2.0 },
  { name: 'Sep', value: 2.8, value2: 2.1 },
  { name: 'Oct', value: 3.0, value2: 2.2 },
  { name: 'Nov', value: 3.2, value2: 2.3 },
  { name: 'Dec', value: 3.5, value2: 2.4 },
];

export const PROPERTY_TYPE_DISTRIBUTION: ChartData[] = [
  { name: 'Commercial', value: 35 },
  { name: 'Residential', value: 45 },
  { name: 'Office', value: 15 },
  { name: 'Industrial', value: 5 },
];

export const ALERTS: Alert[] = [
  {
    id: 'A1',
    title: 'Lease Renewal Required',
    description: '12 leases up for renewal in the next month at Suvarnabhumi Residence.',
    severity: 'warning',
    date: '2 hrs ago',
  },
  {
    id: 'A2',
    title: 'Tenant Dispute',
    description: 'Property 612 DMK: Tenant refuse to leave after contract termination.',
    severity: 'critical',
    date: '5 hrs ago',
  },
  {
    id: 'A3',
    title: 'Fire Safety Compliance',
    description: '3 properties are non-compliant with new fire safety regulations.',
    severity: 'critical',
    date: '1 day ago',
  },
  {
    id: 'A4',
    title: 'Maintenance Scheduled',
    description: 'HVAC maintenance for Park Villa scheduled for next Tuesday.',
    severity: 'info',
    date: '2 days ago',
  },
];

export const LEASES: Lease[] = [
  { 
    id: 'L001', 
    propertyId: 'P001', 
    propertyName: 'Suvarnabhumi - Unit 5F', 
    tenantId: 'tenant-001',
    tenantName: 'TechCorp Inc.', 
    startDate: '2023-01-15', 
    endDate: '2025-12-15', 
    rent: 8500, 
    status: 'expiring', 
    renewalStatus: 'None',
    securityDeposit: 17000,
    createdAt: '2023-01-15T10:00:00Z',
    updatedAt: '2024-11-18T14:30:00Z',
    createdBy: 'admin'
  },
  { 
    id: 'L002', 
    propertyId: 'P003', 
    propertyName: 'Park Villa - 204', 
    tenantId: 'tenant-002',
    tenantName: 'Design Studio LLC', 
    startDate: '2022-06-01', 
    endDate: '2026-05-31', 
    rent: 6200, 
    status: 'active', 
    renewalStatus: 'None',
    securityDeposit: 12400,
    createdAt: '2022-06-01T09:00:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
    createdBy: 'admin'
  },
  { 
    id: 'L003', 
    propertyId: 'P004', 
    propertyName: 'Sriracha View - 8A', 
    tenantId: 'tenant-003',
    tenantName: 'Medical Group', 
    startDate: '2024-03-01', 
    endDate: '2027-02-28', 
    rent: 4800, 
    status: 'active', 
    renewalStatus: 'None',
    securityDeposit: 9600,
    createdAt: '2024-03-01T11:00:00Z',
    updatedAt: '2024-11-10T16:20:00Z',
    createdBy: 'admin'
  },
  { 
    id: 'L004', 
    propertyId: 'P001', 
    propertyName: 'Suvarnabhumi - Unit 3B', 
    tenantId: 'tenant-004',
    tenantName: 'Global Logistics', 
    startDate: '2023-11-01', 
    endDate: '2024-11-01', 
    rent: 7200, 
    status: 'expiring', 
    renewalStatus: 'Draft',
    securityDeposit: 14400,
    createdAt: '2023-11-01T08:30:00Z',
    updatedAt: '2024-11-17T09:15:00Z',
    createdBy: 'admin'
  },
  { 
    id: 'L005', 
    propertyId: 'P005', 
    propertyName: 'Urban Chiang Mai - 101', 
    tenantId: 'tenant-005',
    tenantName: 'Coffee Co.', 
    startDate: '2024-01-01', 
    endDate: '2028-12-31', 
    rent: 12000, 
    status: 'active', 
    renewalStatus: 'Signed',
    securityDeposit: 24000,
    renewalTerms: '5-year term with 3% annual increase',
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-11-18T11:45:00Z',
    createdBy: 'admin'
  },
];

export const WORK_ORDERS: WorkOrder[] = [
  { id: 'WO-123', title: 'HVAC Repair', property: 'Harbor Plaza', priority: 'High', status: 'Submitted', category: 'HVAC' },
  { id: 'WO-124', title: 'Roof Leak', property: 'Oak Street', priority: 'Medium', status: 'Approved', category: 'Structural' },
  { id: 'WO-125', title: 'Paint Job', property: 'Riverside', priority: 'Low', status: 'In Progress', category: 'Cosmetic' },
  { id: 'WO-126', title: 'Electrical Fix', property: 'Harbor Plaza', priority: 'High', status: 'Completed', category: 'Electrical' },
  { id: 'WO-127', title: 'Cleaning', property: 'Oak Street', priority: 'Low', status: 'Completed', category: 'Janitorial' },
];

export const ACTIVITIES: Activity[] = [
  { id: 'act1', type: 'lease', description: 'New lease signed for Urban Chiang Mai', time: '2 hours ago' },
  { id: 'act2', type: 'maintenance', description: 'HVAC repair completed at Park Villa', time: '4 hours ago' },
  { id: 'act3', type: 'financial', description: 'Monthly rent roll generated', time: '5 hours ago' },
  { id: 'act4', type: 'system', description: 'System backup completed successfully', time: '1 day ago' },
  { id: 'act5', type: 'lease', description: 'Lease renewal notice sent to TechCorp', time: '1 day ago' },
];

export const TASKS: Task[] = [
  { 
    id: 't1', 
    title: 'Review Q3 Financial Report', 
    description: 'Review and analyze the Q3 financial report for accuracy and insights',
    status: 'todo', 
    assignee: 'Sarah Chen',
    dueDate: '2024-12-01',
    priority: 'high',
    estimatedHours: 4,
    createdAt: '2024-11-15T10:00:00Z',
    updatedAt: '2024-11-15T10:00:00Z',
    createdBy: 'admin'
  },
  { 
    id: 't2', 
    title: 'Call TechCorp regarding renewal', 
    description: 'Contact TechCorp to discuss lease renewal terms for next year',
    status: 'in_progress', 
    assignee: 'Mike Johnson',
    dueDate: '2024-11-25',
    priority: 'medium',
    parentWorkflowId: 'wf1',
    estimatedHours: 2,
    createdAt: '2024-11-10T09:00:00Z',
    updatedAt: '2024-11-18T14:30:00Z',
    createdBy: 'admin'
  },
  { 
    id: 't3', 
    title: 'Approve Invoice #8492', 
    description: 'Review and approve HVAC maintenance invoice for Park Villa',
    status: 'completed', 
    assignee: 'Lisa Wang',
    dueDate: '2024-11-20',
    priority: 'low',
    actualHours: 1,
    createdAt: '2024-11-14T11:00:00Z',
    updatedAt: '2024-11-19T16:00:00Z',
    createdBy: 'admin'
  },
  { 
    id: 't4', 
    title: 'Schedule elevator maintenance', 
    description: 'Schedule annual elevator maintenance for Urban Chiang Mai',
    status: 'blocked', 
    assignee: 'Tom Davis',
    dueDate: '2024-12-15',
    priority: 'medium',
    blockerReason: 'Waiting for vendor availability confirmation',
    parentWorkflowId: 'wf2',
    estimatedHours: 2,
    createdAt: '2024-11-12T13:00:00Z',
    updatedAt: '2024-11-17T10:30:00Z',
    createdBy: 'admin'
  },
  { 
    id: 't5', 
    title: 'Update tenant insurance records', 
    description: 'Verify and update insurance information for all tenants',
    status: 'todo', 
    assignee: 'Sarah Chen',
    dueDate: '2024-12-10',
    priority: 'critical',
    estimatedHours: 8,
    createdAt: '2024-11-16T15:00:00Z',
    updatedAt: '2024-11-16T15:00:00Z',
    createdBy: 'admin'
  },
];

export const WORKFLOWS: Workflow[] = [
  {
    id: 'wf1',
    title: 'Q1 Budget Review',
    description: 'Comprehensive review and approval of Q1 2025 budget across all properties',
    status: 'active',
    assignee: 'Sarah Chen',
    dueDate: '2025-03-31',
    priority: 'high',
    createdAt: '2024-11-01T09:00:00Z',
    updatedAt: '2024-11-15T14:30:00Z',
    createdBy: 'admin',
    taskIds: ['t1', 't2']
  },
  {
    id: 'wf2',
    title: 'Year-End Maintenance Planning',
    description: 'Plan and schedule all critical maintenance activities for year-end',
    status: 'draft',
    assignee: 'Mike Johnson',
    dueDate: '2024-12-31',
    priority: 'medium',
    createdAt: '2024-11-10T11:00:00Z',
    updatedAt: '2024-11-10T11:00:00Z',
    createdBy: 'admin',
    taskIds: ['t4']
  },
  {
    id: 'wf3',
    title: 'Lease Renewal Campaign 2025',
    description: 'Proactive outreach and renewal process for leases expiring in Q1 2025',
    status: 'active',
    assignee: 'Lisa Wang',
    dueDate: '2025-02-28',
    priority: 'critical',
    propertyId: 'P001',
    createdAt: '2024-11-05T10:00:00Z',
    updatedAt: '2024-11-18T16:45:00Z',
    createdBy: 'admin'
  },
  {
    id: 'wf4',
    title: 'Fire Safety Compliance Audit',
    description: 'Audit and ensure all properties meet new fire safety regulations',
    status: 'completed',
    assignee: 'Tom Davis',
    dueDate: '2024-11-30',
    priority: 'high',
    createdAt: '2024-10-15T08:00:00Z',
    updatedAt: '2024-11-20T12:00:00Z',
    createdBy: 'admin'
  }
];

export const MAINTENANCE_REQUESTS: MaintenanceRequest[] = [
  {
    id: 'mr1',
    propertyId: 'P001',
    propertyName: 'Suvarnabhumi Residence',
    description: 'HVAC system not cooling properly in common areas',
    status: 'submitted',
    priority: 'high',
    costEstimate: 5000,
    category: 'HVAC',
    createdAt: '2024-11-18T09:00:00Z',
    updatedAt: '2024-11-18T09:00:00Z',
    createdBy: 'admin'
  },
  {
    id: 'mr2',
    propertyId: 'P003',
    propertyName: 'Park Villa',
    description: 'Water leak in ceiling of unit 204',
    status: 'assigned',
    priority: 'urgent',
    assignee: 'QuickFix Plumbing',
    costEstimate: 2500,
    scheduledDate: '2024-11-22T10:00:00Z',
    category: 'Plumbing',
    createdAt: '2024-11-17T14:30:00Z',
    updatedAt: '2024-11-19T11:15:00Z',
    createdBy: 'admin'
  },
  {
    id: 'mr3',
    propertyId: 'P005',
    propertyName: 'Urban Chiang Mai',
    description: 'Replace broken security camera at main entrance',
    status: 'in_progress',
    priority: 'medium',
    assignee: 'SecurityPro Services',
    costEstimate: 1200,
    actualCost: 1350,
    scheduledDate: '2024-11-20T14:00:00Z',
    category: 'Security',
    createdAt: '2024-11-15T10:00:00Z',
    updatedAt: '2024-11-20T15:30:00Z',
    createdBy: 'admin'
  },
  {
    id: 'mr4',
    propertyId: 'P002',
    propertyName: 'Airport Side Apartment',
    description: 'Paint touch-ups in hallway and stairwell areas',
    status: 'completed',
    priority: 'low',
    assignee: 'HandyMan Services',
    costEstimate: 800,
    actualCost: 750,
    completionDate: '2024-11-16T17:00:00Z',
    category: 'Cosmetic',
    createdAt: '2024-11-10T08:00:00Z',
    updatedAt: '2024-11-16T17:00:00Z',
    createdBy: 'admin'
  },
  {
    id: 'mr5',
    propertyId: 'P004',
    propertyName: 'Sriracha View',
    description: 'Emergency generator inspection and maintenance',
    status: 'submitted',
    priority: 'high',
    costEstimate: 3000,
    category: 'Electrical',
    createdAt: '2024-11-19T13:45:00Z',
    updatedAt: '2024-11-19T13:45:00Z',
    createdBy: 'admin'
  }
];