import { useChat } from '../context/ChatContext';
import { X, MessageCircle, Sparkles, Lightbulb, TrendingUp, MessageSquare } from 'lucide-react';
import { ChartVisual, MapVisual } from './Visuals';

const InsightModal = () => {
  const { isInsightOpen, closeInsight, insightData, isInsightLoading, insightVisual, openChatWithPrompt } = useChat();

  if (!isInsightOpen) return null;

  const handleAskAssistance = () => {
    const prompt = insightData 
        ? `I have a question about the insight: "${insightData.title}".` 
        : "I need assistance with this data.";
    closeInsight();
    // Small timeout to allow modal to close before opening chat
    setTimeout(() => {
        openChatWithPrompt(prompt);
    }, 300);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 lg:p-8" style={{fontFamily: "'Inter', sans-serif"}}>
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/40 backdrop-blur-sm transition-opacity"
        onClick={closeInsight}
      ></div>

      {/* Modal Card - Expanded Viewport */}
      <div className="bg-white rounded-2xl shadow-2xl w-full h-full max-w-[95vw] max-h-[92vh] relative overflow-hidden flex flex-col lg:flex-row animate-in fade-in zoom-in-95 duration-200 border border-gray-100">
        
        {/* Close Button */}
        <button 
            onClick={closeInsight}
            className="absolute top-4 right-4 p-2 rounded-full hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition-colors z-20"
        >
            <X size={24} />
        </button>

        {/* LEFT PANE: Visual Context (70%) */}
        <div className="lg:w-[70%] h-[40vh] lg:h-full bg-slate-50 border-b lg:border-b-0 lg:border-r border-slate-200 p-6 flex flex-col relative">
            {insightVisual ? (
                <>
                    <div className="mb-4">
                        <h2 className="text-xl font-bold text-slate-800">{insightVisual.title}</h2>
                        <p className="text-sm text-slate-500">Visual Context</p>
                    </div>
                    <div className="flex-1 rounded-xl bg-white border border-slate-200 shadow-sm p-4 overflow-hidden relative">
                        {insightVisual.type === 'chart' && (
                            <ChartVisual 
                                data={{ ...insightVisual.data, chartType: insightVisual.chartType }} 
                                theme="light" 
                            />
                        )}
                        {insightVisual.type === 'map' && (
                            <MapVisual 
                                data={insightVisual.data} 
                                theme="light" 
                            />
                        )}
                    </div>
                </>
            ) : (
                <div className="flex-1 flex items-center justify-center text-slate-400">
                    <div className="text-center">
                        <div className="w-16 h-16 bg-slate-200 rounded-full mx-auto mb-4 flex items-center justify-center">
                            <TrendingUp size={24} className="opacity-50" />
                        </div>
                        <p>No visual context available</p>
                    </div>
                </div>
            )}
        </div>

        {/* RIGHT PANE: AI Insights (30%) */}
        <div className="lg:w-[30%] h-full bg-white flex flex-col overflow-hidden">
            
            {/* Header */}
            <div className="p-6 border-b border-slate-100 bg-gradient-to-r from-blue-50/50 to-white">
                <div className="flex items-center gap-3 mb-1">
                    <div className="w-8 h-8 rounded-lg bg-blue-600 text-white flex items-center justify-center shadow-blue-200 shadow-lg">
                        <Sparkles size={16} />
                    </div>
                    <h2 className="font-bold text-slate-800">AI Analysis</h2>
                </div>
                <p className="text-xs text-slate-500 pl-11">Generated by Gemini 2.5</p>
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 overflow-y-auto p-6 custom-scrollbar">
                {isInsightLoading ? (
                    <div className="flex flex-col items-center justify-center h-64 space-y-4">
                        <div className="w-10 h-10 rounded-xl bg-blue-50 flex items-center justify-center">
                            <Sparkles className="text-blue-500 animate-spin" size={20} />
                        </div>
                        <div className="space-y-2 text-center max-w-[200px]">
                            <div className="h-2 bg-slate-100 rounded w-full animate-pulse"></div>
                            <div className="h-2 bg-slate-100 rounded w-3/4 mx-auto animate-pulse"></div>
                        </div>
                        <p className="text-xs text-slate-400 font-medium animate-pulse">Analyzing data patterns...</p>
                    </div>
                ) : insightData ? (
                    <div className="space-y-8">
                        {/* Title */}
                        <div>
                            <h3 className="font-bold text-lg text-slate-800 leading-snug">{insightData.title}</h3>
                        </div>

                        {/* Explanation */}
                        <div className="space-y-3">
                            <div className="flex items-center gap-2 text-sm font-bold text-slate-700 uppercase tracking-wide">
                                <MessageCircle size={16} className="text-blue-500" />
                                Explanation
                            </div>
                            <div className="bg-slate-50 rounded-xl p-4 border border-slate-100">
                                <ul className="space-y-3">
                                    {insightData.explanation.map((point, idx) => (
                                        <li key={idx} className="text-sm text-slate-600 leading-relaxed flex gap-2">
                                            <span className="mt-1.5 w-1 h-1 rounded-full bg-slate-400 shrink-0"></span>
                                            {point}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        </div>

                        {/* Prediction */}
                        <div className="space-y-3">
                            <div className="flex items-center gap-2 text-sm font-bold text-slate-700 uppercase tracking-wide">
                                <TrendingUp size={16} className="text-purple-500" />
                                Prediction
                            </div>
                            <p className="text-sm text-slate-600 leading-relaxed italic pl-4 border-l-2 border-purple-200">
                                "{insightData.prediction}"
                            </p>
                        </div>

                        {/* Suggestions */}
                        <div className="space-y-3">
                            <div className="flex items-center gap-2 text-sm font-bold text-slate-700 uppercase tracking-wide">
                                <Lightbulb size={16} className="text-amber-500" />
                                Suggestions
                            </div>
                            <div className="space-y-2">
                                {insightData.suggestions.map((suggestion, idx) => (
                                    <div key={idx} className="flex items-start gap-3 p-3 rounded-lg border border-amber-100 bg-amber-50/50 hover:bg-amber-50 transition-colors">
                                        <div className="w-5 h-5 rounded-full bg-white border border-amber-200 text-amber-600 flex items-center justify-center shrink-0 text-[10px] font-bold shadow-sm">
                                            {idx + 1}
                                        </div>
                                        <span className="text-sm text-slate-700 font-medium">{suggestion}</span>
                                    </div>
                                ))}
                            </div>
                        </div>
                    </div>
                ) : (
                    <div className="text-center text-red-500 py-10">
                        Unable to load insights. Please try again.
                    </div>
                )}
            </div>

            {/* Footer Action */}
            <div className="p-4 border-t border-slate-100 bg-white">
                <button 
                    onClick={handleAskAssistance}
                    className="w-full flex items-center justify-center gap-2 bg-slate-800 hover:bg-slate-900 text-white py-3 rounded-xl font-medium transition-all shadow-lg shadow-slate-200"
                >
                    <MessageSquare size={18} />
                    <span>Ask Assistant</span>
                </button>
            </div>
        </div>
      </div>
    </div>
  );
};

export default InsightModal;